### ISSUE TITLE
No module named "example", when I try to run application from example

### ISSUE THREAD

**Issue by krosenmann** [zenwalker/django-micro#15]
> (.venv) ~/sources/wisdomchest/django-micro/example$ python app.py migrate                                                                     
Traceback (most recent call last):                                                                                                                                       
  File "app.py", line 19, in <module>
    configure(locals(), django_admin=True)
  File "/home/roman/sources/wisdomchest/.venv/lib/python3.6/site-packages/django_micro.py", line 83, in configure
    _create_app(inspect.stack())  # load application from parent module
  File "/home/roman/sources/wisdomchest/.venv/lib/python3.6/site-packages/django_micro.py", line 34, in _create_app
    import_module(app_module)
  File "/home/roman/sources/wisdomchest/.venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                                                                      
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked                                                                                             
ModuleNotFoundError: No module named 'example'                                                                                                                           

If I try to import this module from +1 level of file system then importing work correctly either running with uwsgi. 
Uwsgi backtrace from `example` folder shows the same error. 

I found that U cannot import module when U stay in imported module folder. It looks like a reason. 

Django 2.0.8, python 3.6

**Comment by krosenmann** [comment]
And with `sys.path.append('..')` everything works fine, but adding this string to every project looks kinda stupid.

**Comment by maxpoletaev** [comment]
Seems I accidentally removed a line that uses the parent directory as the import root in one of the latest commits. I’ll fix this asap! Thank you for reporting!

**Comment by maxpoletaev** [comment]
Fixed in 1.7.2
